# Generated by Django 5.2.6 on 2025-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0009_epica_tarea_epica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epica',
            name='sprint',
        ),
        migrations.AddField(
            model_name='epica',
            name='sprints',
            field=models.ManyToManyField(blank=True, related_name='epicas', to='backlog.sprint'),
        ),
    ]
