# Generated by Django 5.2.6 on 2025-10-16 17:52

import backlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0010_remove_epica_sprint_epica_sprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='esfuerzo_sp',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Story points (1, 2, 3, 5, 8, 13, 21)', null=True, validators=[backlog.models.validar_story_points]),
        ),
    ]
