# Generated by Django 5.2.6 on 2025-10-17 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0011_tarea_esfuerzo_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador corto del proyecto (ej. NEUCONTA, CPS, JURIDICO).', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='epica',
            name='avance_manual',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–100. Si se deja vacío, se calcula por tareas.', null=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código legible de la épica (ej. NEUSI-001).', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='documentos_url',
            field=models.URLField(blank=True, help_text='Enlace a carpeta o documento maestro'),
        ),
        migrations.AddField(
            model_name='epica',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epica',
            name='kpis',
            field=models.TextField(blank=True, help_text='Métricas clave esperadas para la épica'),
        ),
        migrations.AddField(
            model_name='epica',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta épica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epicas', to='backlog.proyecto'),
        ),
    ]
