# Generated by Django 5.2.6 on 2025-10-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0012_epica_proyecto_campos_nuevos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignados',
            field=models.ManyToManyField(blank=True, related_name='tareas_asignadas', to='backlog.integrante'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas_legacy', to='backlog.integrante'),
        ),
    ]
