# Generated by Django 5.2.6 on 2025-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0013_tarea_asignados_alter_tarea_asignado_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='epica',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Responsables/co-owners de la épica', related_name='epicas_cocreadas', to='backlog.integrante'),
        ),
    ]
