# Generated by Django 5.2.6 on 2025-10-21 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0014_epica_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='rol',
            field=models.CharField(choices=[('Scrum Master / PO', 'Scrum Master / PO'), ('Arquitecto de Software y Director General', 'Arquitecto de Software y Director General'), ('Visualizador', 'Visualizador'), ('Product Owner Coofisam360', 'Product Owner Coofisam360'), ('Administrador de Bases de Datos (DBA)', 'Administrador de Bases de Datos (DBA)'), ('Líder Comercial', 'Líder Comercial'), ('Especialista en Visualización y BI', 'Especialista en Visualización y BI'), ('Desarrollador Frontend', 'Desarrollador Frontend'), ('Desarrollador Backend', 'Desarrollador Backend'), ('Coordinadora de Marketing y Comunicación', 'Coordinadora de Marketing y Comunicación'), ('Coordinadora de Gestión Humana y Administrativa', 'Coordinadora de Gestión Humana y Administrativa'), ('Contadora General', 'Contadora General'), ('Miembro', 'Miembro')], default='Miembro', max_length=100),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrante', to=settings.AUTH_USER_MODEL),
        ),
    ]
