# Generated by Django 5.2.6 on 2025-10-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0015_alter_integrante_rol_alter_integrante_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='epica',
            options={'managed': True, 'ordering': ['-creada_en']},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': True, 'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'managed': True},
        ),
    ]
