# Generated by Django 5.2.6 on 2025-10-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0016_alter_daily_options_alter_epica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='epica',
            options={'managed': False, 'ordering': ['-creada_en']},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': False, 'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='PermisoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_proyecto', to='backlog.integrante')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_integrantes', to='backlog.proyecto')),
            ],
            options={
                'verbose_name': 'Permiso de Proyecto',
                'verbose_name_plural': 'Permisos de Proyecto',
                'managed': True,
                'unique_together': {('integrante', 'proyecto')},
            },
        ),
    ]
