# Generated by Django 5.2.6 on 2025-10-24 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0017_alter_daily_options_alter_epica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisoproyecto',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='permisoproyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permisoproyecto',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='permisoproyecto',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_proyectos', to='backlog.integrante'),
        ),
        migrations.AlterModelTable(
            name='permisoproyecto',
            table='backlog_permisoproyecto',
        ),
    ]
