# Generated by Django 5.2.6 on 2025-11-01 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0019_alter_permisoproyecto_options_bloquetarea_subtarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtarea',
            name='bloque',
        ),
        migrations.RemoveField(
            model_name='subtarea',
            name='responsable',
        ),
        migrations.DeleteModel(
            name='BloqueTarea',
        ),
        migrations.DeleteModel(
            name='Subtarea',
        ),
    ]
