# Generated by Django 5.2.6 on 2025-11-01 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0020_remove_subtarea_bloque_remove_subtarea_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveSmallIntegerField(help_text='Orden del bloque dentro de la tarea (1,2,3,...)')),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='backlog.tarea')),
            ],
            options={
                'db_table': 'backlog_bloquetarea',
                'ordering': ['indice', 'id'],
                'managed': True,
                'unique_together': {('tarea', 'indice')},
            },
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('entregada', 'Entregada'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='backlog.bloquetarea')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtareas_responsable', to='backlog.integrante')),
            ],
            options={
                'db_table': 'backlog_subtarea',
                'ordering': ['bloque__indice', 'id'],
                'managed': True,
            },
        ),
    ]
