# Generated by Django 5.2.6 on 2025-11-01 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0021_bloquetarea_subtarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaSubtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias_subtareas/%Y/%m')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evid_subt_creador', to=settings.AUTH_USER_MODEL)),
                ('subtarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='backlog.subtarea')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
