# Generated by Django 5.2.6 on 2025-11-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0022_evidenciasubtarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtarea',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='esfuerzo_sp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5')], null=True),
        ),
    ]
