# Generated by Django 5.2.6 on 2025-11-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0023_subtarea_descripcion_subtarea_esfuerzo_sp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquetarea',
            options={'managed': False, 'ordering': ['indice', 'id']},
        ),
        migrations.AlterModelOptions(
            name='daily',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subtarea',
            options={'managed': False, 'ordering': ['bloque__indice', 'id']},
        ),
        migrations.CreateModel(
            name='DailyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AYER', 'Ayer'), ('HOY', 'Hoy')], max_length=4)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('evidencia_url', models.URLField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backlog.daily')),
                ('subtarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_items', to='backlog.subtarea')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_items', to='backlog.tarea')),
            ],
            options={
                'db_table': 'backlog_dailyitem',
                'managed': True,
                'indexes': [models.Index(fields=['daily_id'], name='idx_ditem_daily'), models.Index(fields=['tipo'], name='idx_ditem_tipo'), models.Index(fields=['tarea_id'], name='idx_ditem_tarea'), models.Index(fields=['subtarea_id'], name='idx_ditem_subtarea')],
            },
        ),
    ]
