# Generated by Django 5.2.6 on 2025-11-07 02:41

import backlog.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0024_alter_bloquetarea_options_alter_daily_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 7, 2, 41, 22, 971253, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daily',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailies', to='backlog.sprint'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='daily',
            name='hora',
            field=models.TimeField(default=backlog.models.now_local_time),
        ),
        migrations.AlterField(
            model_name='daily',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies', to='backlog.integrante'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='que_hara_hoy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='daily',
            name='que_hizo_ayer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='daily',
            index=models.Index(fields=['fecha'], name='idx_daily_fecha'),
        ),
        migrations.AddIndex(
            model_name='daily',
            index=models.Index(fields=['integrante', 'fecha'], name='idx_daily_int_fec'),
        ),
        migrations.AddConstraint(
            model_name='daily',
            constraint=models.UniqueConstraint(fields=('integrante', 'fecha'), name='uniq_daily_integrante_fecha'),
        ),
        migrations.AlterModelTable(
            name='daily',
            table='backlog_daily',
        ),
    ]
