# Generated by Django 5.2.6 on 2025-10-21 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadsemanal',
            options={'ordering': ('-semana_inicio',)},
        ),
        migrations.RenameField(
            model_name='disponibilidadsemanal',
            old_name='actualizado_en',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='disponibilidadsemanal',
            old_name='creado_en',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='disponibilidadsemanal',
            name='actualizado_por',
        ),
        migrations.AlterField(
            model_name='disponibilidadsemanal',
            name='semana_inicio',
            field=models.DateField(help_text='Lunes de la semana'),
        ),
        migrations.AlterField(
            model_name='disponibilidadsemanal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_disponibilidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DisponibilidadDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('tipo', models.CharField(choices=[('D', 'Disponible todo el día'), ('N', 'No disponible'), ('R', 'Rango de disponibilidad')], default='N', max_length=1)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='disponibilidad.disponibilidadsemanal')),
            ],
            options={
                'ordering': ('dia_semana',),
                'unique_together': {('disponibilidad', 'dia_semana')},
            },
        ),
        migrations.DeleteModel(
            name='HorarioDisponibilidad',
        ),
    ]
