# Generated by Django 5.2.6 on 2025-10-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0002_alter_disponibilidadsemanal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidaddia',
            options={'managed': True, 'ordering': ('dia_semana',)},
        ),
        migrations.AlterModelOptions(
            name='disponibilidadsemanal',
            options={'managed': True, 'ordering': ('-semana_inicio',)},
        ),
    ]
