# Generated by Django 5.2.6 on 2025-11-01 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0003_alter_disponibilidaddia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidaddia',
            options={'managed': False, 'ordering': ('dia_semana',)},
        ),
    ]
